version: '3.2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        container_name: cloud_elasticsearch
        networks:
            - my_index_cloud
        environment:
            - network.host=0.0.0.0
            - discovery.type=single-node
            - cluster.name=docker-cluster
            - node.name=cluster1-node1
            - xpack.license.self_generated.type=basic
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            # - http.host=0.0.0.0
            # - http.port=9200
            # - "http.cors.allow-origin=\*"
            # - "http.cors.enabled=true"
            # - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
            # - "http.cors.allow-credentials=true"

        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata2:/usr/share/elasticsearch/data
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
            - 9292:9200

    kibana:
        image: docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT
        container_name: cloud_kibana
        networks:
            - my_index_cloud
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
        depends_on:
            - elasticsearch

    index_cloud:
        # image: python:3.9-buster
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./backend/:/app
            - /home/SRV-VLACloud/nextcloud/data/:/app/dados/
        working_dir: /app
        command: tail -f /dev/null
        networks:
            - my_index_cloud

    index_frontend:
        image: node:18.12.1
        volumes:
            - ./frontend/:/app
        working_dir: /app
        command: bash -c "npm install && npm start"
        ports:
            - "3000:3000"
        networks:
            - my_index_cloud

    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: ldap
            MYSQL_USER: ldap
            MYSQL_PASSWORD: ldap

    ldap:
        image: osixia/openldap
        environment:
            LDAP_ORGANISATION: "VLA Cloud"
            LDAP_DOMAIN: "ldap.dpf.vla.com"
            LDAP_ADMIN_PASSWORD: "admin"
        volumes:
            - ldap_data:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d
        ports:
            - 389:389
        restart: always

    phpldapadmin:
        image: osixia/phpldapadmin
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap
        ports:
            - 6443:443
        restart: always

volumes:
    db_data:
        driver: local
    ldap_data:
        driver: local
    ldap_config:
        driver: local
    esdata2:
        driver: local
networks:
    my_index_cloud:
        name: my_index_cloud
        driver: bridge
